runc: fix PKG_SOURCE_VERSION
While building docker-ce, it fails because of:
ERROR: Expected 'PKG_SOURCE_VERSION:=dc9208a3303feef5b3839f4323d9beb36df0a9dd' in '../runc/Makefile', found 'PKG_SOURCE_VERSION:=ff819c7e9184c13b7c2607fe6c30ae19403a7aff'

Fixes: #2

Signed-off-by: Josef Schlehofer <pepe.schlehofer@gmail.com>