zabbix: zabbix-server-frontend: update dependency
Only show zabbix-server-frontend if the build dependency 'PACKEGE_php8' is
fulfilled. This means that 'zabbix-server-frotend' can only be selected if
PHP has also been enabled for building.

This change is needed to fix the following recursive dependency warning.

error: recursive dependency detected!
   symbol PACKAGE_php8 is selected by PACKAGE_zabbix-server-frontend
   symbol PACKAGE_zabbix-server-frontend depends on PHP8_DOM
   symbol PHP8_DOM depends on PACKAGE_php8
For a resolution refer to Documentation/kbuild/kconfig-language.rst

Signed-off-by: Florian Eckert <fe@dev.tdt.de>
(cherry picked from commit dec74a798599c935b454804114ecf7af5713e09e)