fibocom-qmi-wwan: fix build error "missing-prototypes"
to fix the following error:

make[4]: Entering directory '/mnt/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.12.31'
  CC [M]  /mnt/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/fibocom-qmi-wwan-1.0.5/qmi_wwan_f.o
/mnt/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/fibocom-qmi-wwan-1.0.5/qmi_wwan_f.c:1334:5: error: no previous prototype for 'qma_setting_store' [-Werror=missing-prototypes]
 1334 | int qma_setting_store(struct device *dev, QMAP_SETTING *qmap_settings, size_t size) {
      |     ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[6]: *** [scripts/Makefile.build:229: /mnt/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/fibocom-qmi-wwan-1.0.5/qmi_wwan_f.o] Error 1
make[5]: *** [/mnt/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/linux-6.12.31/Makefile:1945: /mnt/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/linux-mediatek_filogic/fibocom-qmi-wwan-1.0.5] Error 2

build tested on BPi-R3 mini with FM150-AE

Signed-off-by: Rye Sears <xlighting@gmail.com>