mdio-tools: add kmod-mdio-netlink as dependencies
Otherwise it will fail as follows:
  failed to find a module named mdio-netlink
  ERROR: mdio-netlink module not detected, and could not be loaded.

Run-tested on: ramips/mt7621

Signed-off-by: Chukun Pan <amadeus@jmu.edu.cn>
(cherry picked from commit 5c3d27677f8295d9a14be7ddff4567114d88da99)