glib2: fix builds by explicitly disabling libelf
The libelf Meson option defaults to auto. Since commit 71b7b4478906 ("glib2: do not set default meson options"),
glib2 can enable libelf support nondeterministically depending on whether libelf.pc is visible during configure.

On failing builders Meson reports:

    Run-time dependency libelf found: YES 0.192

 and gresource later fails with:

    ../gio/gresource-tool.c:34:10: fatal error: libelf.h: No such file or directory

On passing builders we see:

    Run-time dependency libelf found: NO (tried pkgconfig and cmake)

So explicitly disable libelf again to restore deterministic builds.

Fixes: #23459
Fixes: 71b7b4478906 ("glib2: do not set default meson options")
Signed-off-by: Lu Dai <lu.dai@mind.be>
Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>